### ISSUE TITLE
Dark Enchantment General Lore

### ISSUE THREAD

**Issue by frqnny** [frqnny/dark-enchanting#2]
Lore
-
In the Dark Ages, Mages and Enchantress were prosecuted by the Church. Pushed to the edges of the world, they banded together and formed a secret society where they would be safe.  Together, they accomplished thousands of breakthroughs in enchanting & magic. Grand monuments and dungeons were built to honor these accomplishments. One day, the society mysteriously vanished, leaving the monuments - and 4 Holy Books. 
Without a doubt, they left it to you, [player name], to revive this lost, yet simple magic.

Dark Enchanting attempts to have a magic mod with very little tech mod aspects, but rather promote the adventure & beauty of magic. Magic mods tend to actually be tech mods with a magic facade- mana/RF, cables/mana paths or whatever, you get the picture. Magic mods should instead be about exploring the unknown, the fantasy, and immersing the player in exciting and new content. The expansion of the enchantment content in Minecraft is therefore an ideal magic aspect to target. Using particles, mobs, and more immersive magic, we are able to introduce an expansive magic mod.

Dark Enchantment Categories
-
- Sin vitae
- Dies Irae
- Lux Aeterna
- Paradisum
To use each enchantment, it is available through Holy Books. The first is obtainable through a costly craft. Dies Irae is obtainable through a dungeon in the Overworld, Lux Aeterna in the Nether, and Paradisum in the End. More on dungeons later. 

Sin Vitae Enchantments - all curses
-
- Lust
- Gluttony
- Greed
- Sloth
- Wrath
- Envy
- Pride

Dies Irae Enchantments
-
- Vampiric Friendship
- Zombified Love
- Skeletal Courage
- Arachnid Honesty
- Ghastly Intervention
- Draconic Intervention
- Poisening Death
- Withering Death

Lux Aeterna Enchantments
-
- 

Paradisum Enchantments
-
- Castitas (Chastity)
- Moderatio (Temperance)
- Liberalitas (Generosity)
- Industria (Diligence)
- Patientia (Patience)
- Gratia (Gratitude)
- Humilitas (Humility)

**Comment by Rakkis157** [comment]
Enchantress -> Enchantresses
