### ISSUE TITLE
Request: Forge version for 1.16.5+

### ISSUE THREAD

**Issue by IITFA** [frqnny/dark-enchanting#4]
Based on the description on CurseForge, this is exactly what is needed for 1.16.5+. Nothing else exists like it for Forge that I can find. This type of mod is what I miss most about 1.12.2. I know a lot of people have asked in the CurseForge comments, but this "issue" is simply an "official request" that I really hope is fulfilled. Thank you.

**Comment by frqnny** [comment]
No.
