### ISSUE TITLE
Dark Enchanter repairs items

### ISSUE THREAD

**Issue by ConqAra** [frqnny/dark-enchanting#6]
When enchanting with dark enchanter it automatically repairs your items. Even if you don't enchant it and just put it in the dark enchanter and take it back out, it will repair the item.

**Comment by ConqAra** [comment]
Gif of bug: https://i.imgur.com/BK2s70M.gif

**Comment by frqnny** [comment]
Sorry for finally getting to the issue but I cannot replicate.

**Comment by ConqAra** [comment]
maybe its a mod incompatibility? I had a few mods on, I'll look into it again

**Comment by frqnny** [comment]
Alright. I released a new update so check with that too.

**Comment by ConqAra** [comment]
Seems to be fine now
