### ISSUE TITLE
Dark Enchanting table bug making you pay levels for no reason.

### ISSUE THREAD

**Issue by ConqAra** [frqnny/dark-enchanting#7]
For some reason there's a bug (only with sharpness and looting as of now) in the table, where if you place an item into the enchantment table you ALREADY have a level fine to pay. It should be zero to start off with until you start increasing the sliders but for some reason the table thinks you were already increasing the slider beforehand, thus demanding levels to pay without even adding/upgrading more enchantments on the equipment. 

The gold boots had no enchantment requested yet needed 44 levels anyways. And for some reason the golden sword had no enchantments yet the table already thought it had sharpness and looting, but still demanding the levels.

gif of bug: https://streamable.com/bqlx6n

**Comment by frqnny** [comment]
Thanks for the bug reports.
